<a href="https://colab.research.google.com/github/yeamuhid/Another-Fluid-Flow-Analysis-in-Biomedical-Images-Using-Image-Processing-and-Machine-Learning-02/blob/main/Save_Model_Using_Joblib_And_Pickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import pandas as pd
import numpy as np
from sklearn import linear_model



In [7]:
df = pd.read_csv("/content/drive/MyDrive/CODE/a.csv")
df.head()

Unnamed: 0  area   price
0           0  2600  550000
1           1  3000  565000
2           2  3200  610000
3           3  3600  680000
4           4  4000  725000

In [12]:
model = linear_model.LinearRegression()
model.fit(df[['area',]],df.price)

LinearRegression()

In [ ]:
model = linear_model.LinearRegression()
model.fit(df[['area',]],df.price)

In [ ]:
model = linear_model.LinearRegression()
model.fit(df[['area',]],df.price)

In [13]:
model.coef_

array([135.78767123])

In [14]:
model.intercept_

180616.43835616432

In [25]:
model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [26]:
import pickle


In [29]:
with open('model_pickle','wb') as f:
  pickle.dump(model,f)

In [45]:
with open('model_pickle','rb') as f:
  mp =pickle.load(f)

In [46]:
mp.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [61]:
from sklearn.externals import joblib
import os

ImportError: cannot import name 'joblib' from 'sklearn.externals' (/usr/local/lib/python3.10/dist-packages/sklearn/externals/__init__.py)

In [57]:
joblib.dump(model, 'model_joblib')

NameError: name 'model' is not defined

In [55]:
mj = joblib.load('model_joblib')

FileNotFoundError: [Errno 2] No such file or directory: 'model_joblib'

In [ ]:
mj .predict([[5000]])
mi.coef_
mj.intercept_